### ISSUE TITLE
./configure needs ada-wiki

### ISSUE THREAD

**Issue by ghost** [stcarrez/ada-awa#1]
./configure wants ada-wiki-1.0.0.tar.gz, which is not found in distrib dir. Should it be there, or should README be modified to let the user know ada-wiki must be compiled separately?

**Comment by stcarrez** [comment]
Thanks for the report.
The distrib dir is not ready yet to be used with the git repository. It is intended to be used
for the final tar ball when a new release of AWA is done.

To solve this issue, I have added a configure option **--with-git** to get and use the repositories
that AWA depends on.  I've managed to make the whole configure and build process work with
that option.

This is now documented in [Installation](https://github.com/stcarrez/ada-awa/wiki/Installation).

**Comment by stcarrez** [comment]
The --with-git option was replaced by git submodules.  I've updated the documentation.
