### ISSUE TITLE
Unable to configure on Windows

### ISSUE THREAD

**Issue by basis0** [stcarrez/ada-awa#11]
When running

./configure --prefix=/usr/local

On Windows 10 within msys2 I get the following:

***
configure: error: Building Ada EL requires the Ada Utility Library.
  You should build and install the Ada Utility Library component.
  It must be available and found by gprbuild.
  This project was not found in the ADA_PROJECT_PATH environment variable.
  This project was not found in ../utilada_base nor in ../ada-util-*.
  The component is available at git@github.com:stcarrez/ada-util.git.
  Please, download and configure Ada Utility Library.
  The current configuration was using:
    gprbuild
    ADA_PROJECT_PATH=

configure: error: ./configure failed for ada-el
***

I would assume any interdependencies on the modules would have been handled so I am a little uncertain if this is the ada-util module or something else.  Thank you very much!

**Comment by stcarrez** [comment]
I apologize for my late answer. Thanks for the bug report. The above commits are fixing the build.

It's fixed in AWA 2.2.0 release.
