### ISSUE TITLE
Invalid install instructions on wiki installation page

### ISSUE THREAD

**Issue by twdroeger** [stcarrez/ada-awa#2]
The wiki installation page https://github.com/stcarrez/ada-awa/wiki/Installation has the following instructions

git clone git@github.com:stcarrez/ada-awa.git ada-awa
cd ada-awa
./configure --with-git --prefix=$HOME/install-awa

This does not work. The --with-git option is not an available option for the configure script.

Instead I executed the following commands to install ada-awa

git clone --recursive git@github.com:stcarrez/ada-awa.git ada-awa
cd ada-awa
./configure --prefix=$HOME/install-awa

This does work. I was able to configure, build and install ada-awa.

**Comment by stcarrez** [comment]
Thanks for the notice. You are right, I've implemented a --with-git option some time ago
before using git submodules and I've removed it after switching to sub-modules.

**Comment by stcarrez** [comment]
I've updated the installation page.
