### ISSUE TITLE
imported project file "aws" not found

### ISSUE THREAD

**Issue by ethindp** [stcarrez/ada-awa#21]
For some reason the configure script isn't finding the aws installation even though its in the "external" directory. Ideas or should I just install it from the AUR?

**Comment by stcarrez** [comment]
If `gnat` fails to find `aws`, it could be that it is installed in some other directory.

Make sure `aws` was compiled and installed and locate the `aws.gpr` file.

Then, setup the `ADA_PROJECT_PATH` environment variable to indicate the location of the installed `aws.gpr` file.

If you have installed `aws.gpr` in `/usr/local/share/gpr`, then you should set:

```
export ADA_PROJECT_PATH=/usr/local/share/gpr
```

**Comment by ethindp** [comment]
Oh... Whoops? I understand how it works now. I saw aws under external/aws and thought that aws was a submodule. Thanks!
