### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by eqcola** [stcarrez/ada-awa#4]
Hello, i'm getting started on Linux platform (Centos 7) and after I build my web app "hello" when server run I've the 404 on http://localhost:8080/hello/index.html 
The server log say:

INFO : Reading module configuration file setup.xml
INFO : Reading file setup.xml
**ERROR: setup.xml: File 'setup.xml' does not exist.**

`
[root@vmcentos7` hello]# bin/hello-server
INFO : Register bindings: http://java.sun.com/jsf/core
INFO : Register bindings: http://java.sun.com/jsf/html
INFO : Register bindings: http://java.sun.com/jstl/core
INFO : Register bindings: http://java.sun.com/jsf/facelets
INFO : Register bindings: http://code.google.com/p/ada-asf/util
INFO : Register bindings: http://code.google.com/p/ada-asf/ajax
INFO : Register bindings: http://code.google.com/p/ada-asf/widget
INFO : Register bean class ASF.Beans.Map_Bean
DEBUG: Add namespace fn:http://java.sun.com/jsp/jstl/functions
DEBUG: Adding config log4j.appender.console = Console
DEBUG: Adding config openid.provider.orange = http://openid.orange.fr
DEBUG: Adding config log4j.logger.ASF.Views.Nodes.Reader = INFO
DEBUG: Adding config google-plus.secret = PUT-HERE_GOOGLE-SECRET
DEBUG: Adding config google-plus.client_id = PUT-HERE-GOOGLE-CLIENT-ID.apps.googleusercontent.com
DEBUG: Adding config log4j.logger.ASF = DEBUG
DEBUG: Adding config dynamo_author = eqcola
DEBUG: Adding config log4j.logger.AWA.Modules = WARN
DEBUG: Adding config log4j.logger.AWA = DEBUG
DEBUG: Adding config log4j.appender.result = File
DEBUG: Adding config bundle.dir = bundles
DEBUG: Adding config dynamo_is_lib = FALSE
DEBUG: Adding config app_name = Null
DEBUG: Adding config log4j.appender.result.File = hello.log
DEBUG: Adding config openid.callback_url = http://localhost:8080/hello/auth/verify
DEBUG: Adding config dynamo_is_ado = FALSE
DEBUG: Adding config log4j.rootCategory = DEBUG,console,result
DEBUG: Adding config bundle.var.samplesMsg = samples
DEBUG: Adding config openid.provider.myopenid = http://www.myopenid.com/server
DEBUG: Adding config log4j.logger.Util.Log = WARN
DEBUG: Adding config counters.counter_limit = 10
DEBUG: Adding config contextPath = /hello
DEBUG: Adding config log4j.logger.Util.Serialize.IO = INFO
DEBUG: Adding config database = mysql://localhost:3306/hello?user=hello
DEBUG: Adding config dynamo_is_tool = FALSE
DEBUG: Adding config view.dir = web
DEBUG: Adding config facebook.secret = PUT-HERE-YOUR-FACEBOOK-API-SECRET
DEBUG: Adding config log4j.logger.Util = DEBUG
DEBUG: Adding config openid.realm = http://localhost:8080/hello/auth
DEBUG: Adding config app_search_dirs = .
DEBUG: Adding config log4j.logger.ADO.Databases = INFO
DEBUG: Adding config dynamo_license = apache
DEBUG: Adding config dynamo_is_gtk = FALSE
DEBUG: Adding config awa_dispatcher_count = 0
DEBUG: Adding config dynamo_author_email = eqcola@vodafone.it
DEBUG: Adding config log4j.appender.console.layout = level-message
DEBUG: Adding config openid.provider.yahoo = http://open.login.yahooapis.com/openid20/www.yahoo.com/xrds
DEBUG: Adding config facebook.scope = email
DEBUG: Adding config web.dir = web
DEBUG: Adding config view.escape_unknown_tags = true
DEBUG: Adding config counters.counter_age_limit = 1
DEBUG: Adding config app.modules.dir = config
DEBUG: Adding config log4j.logger.Util.Serialize.Mappers = WARN
DEBUG: Adding config view.debug = true
DEBUG: Adding config dynamo_is_web = TRUE
DEBUG: Adding config view.ext = .html
DEBUG: Adding config openid.provider.google = https://www.google.com/accounts/o8/id
DEBUG: Adding config view.ignore_spaces = false
DEBUG: Adding config log4j.logger.log = WARN
DEBUG: Adding config facebook.client_id = PUT-HERE-YOUR-FACEBOOK-CLIENT-ID
DEBUG: Adding config app.config = awa.xml
DEBUG: Adding config log4j.logger.Util.Properties = DEBUG
DEBUG: Adding config log4j.appender.console.level = DEBUG
DEBUG: Adding config user.auth-filter.redirect = /hello/auth/login.html
DEBUG: Adding config app_url_base = http://localhost:8080
DEBUG: Adding config log4j.logger.AWA.Applications.Configs = WARN
INFO : Set facelet search directory to: 'web'
INFO : Initialize bundle factory to load from bundles
INFO : Register bean 'samplesMsg' in scope
INFO : Using page /setup/install.html for http error  404
INFO : Add servlet 'redirect'
INFO : Add servlet 'faces'
INFO : Add servlet 'files'
INFO : File servlet using directory 'web'
INFO : Add servlet mapping *.html -> redirect
INFO : Adding route *.html
INFO : Add servlet mapping /setup/*.html -> faces
INFO : Adding route /setup/*.html
INFO : Add servlet mapping *.css -> files
INFO : Adding route *.css
INFO : Add servlet mapping *.js -> files
INFO : Adding route *.js
INFO : Add servlet mapping *.png -> files
INFO : Adding route *.png
INFO : Register bindings: http://code.google.com/p/ada-awa/jsf
DEBUG: Add namespace fn:http://java.sun.com/jsp/jstl/functions
INFO : Reading module configuration file setup.xml
INFO : Reading file setup.xml
ERROR: setup.xml: File 'setup.xml' does not exist.
INFO : Get driver mysql
INFO : Register driver mysql
INFO : Register driver sqlite
INFO : Set connection URI: mysql://localhost:3306/hello?user=hello 
`

Thanks in advance.
Regards

**Comment by stcarrez** [comment]
It looks like a configuration issue where the **app_search_dirs** configuration option only contains **'.'**
and it is not able to find the AWA installed files. The AWA files are installed in `/usr/local/share/dynamo`
or `/usr/share/dynamo` directories.  The application configuration file should contain something like:

app_search_dirs=.;#{dynamo_search_dirs}
dynamo_search_dirs=/usr/local/share/dynamo/awa_setup

The **dynamo_search_dirs** configuration property is updated automatically by running the
following command:

make generate

or 

dynamo generate db

**Comment by eqcola** [comment]
Hi, i've added in hello.properties the correct key-value dynamo_search_dirs, so the problem is fixed.

Thanks

**Comment by stcarrez** [comment]
Problem fixed.
