### ISSUE TITLE
Typo in a GPR file

### ISSUE THREAD

**Issue by Heziode** [stcarrez/ada-awa#40]
Small typo in the following GPR file:

https://github.com/stcarrez/ada-awa/blob/3e8786ed10b051588838dd52665205f99413ff76/awa/plugins/awa-wikis/distrib/awa_wikis.gpr#L7

Should be `with`

**Comment by stcarrez** [comment]
Thanks! In fact, the `distrib` files are not used anymore since the GPR installation are made with `gprinstall`.
These files must be removed.
