### ISSUE TITLE
Docker build fails in current checkout

### ISSUE THREAD

**Issue by twdroeger** [stcarrez/ada-awa#5]
I attempted a Docker build using ada-awa/docker/Dockerfile. 

The commands I issued were

```
$ cd ada-awa/docker
$ sudo docker build -t ada-awa .
```

Here is the output showing the build error

```
.
.
.
awa-events-models.ads:37:06: file "ado-audits.ads" not found
awa-events-models.ads:37:06: "AWA.EVENTS.MODELS (body)" depends on "AWA.EVENTS.MODELS (spec)"
awa-events-models.ads:37:06: "AWA.EVENTS.MODELS (spec)" depends on "AWA.USERS.MODELS (spec)"
awa-events-models.ads:37:06: "AWA.USERS.MODELS (spec)" depends on "ADO.AUDITS (spec)"
awa-audits-models.ads:34:06: file "ado-audits.ads" not found
awa-audits-models.ads:34:06: "AWA.AUDITS.MODELS (body)" depends on "AWA.AUDITS.MODELS (spec)"
awa-audits-models.ads:34:06: "AWA.AUDITS.MODELS (spec)" depends on "AWA.USERS.MODELS (spec)"
awa-audits-models.ads:34:06: "AWA.USERS.MODELS (spec)" depends on "ADO.AUDITS (spec)"
awa-oauth-models.ads:34:06: file "ado-audits.ads" not found
awa-oauth-models.ads:34:06: "AWA.OAUTH.MODELS (body)" depends on "AWA.OAUTH.MODELS (spec)"
awa-oauth-models.ads:34:06: "AWA.OAUTH.MODELS (spec)" depends on "AWA.USERS.MODELS (spec)"
awa-oauth-models.ads:34:06: "AWA.USERS.MODELS (spec)" depends on "ADO.AUDITS (spec)"

   compilation of awa-oauth-models.adb failed
   compilation of awa-audits-models.adb failed
   compilation of awa-events-models.adb failed

gprbuild: *** compilation phase failed
rules.mk:108: recipe for target 'local-build' failed
make[1]: *** [local-build] Error 4
Makefile:119: recipe for target 'build' failed
make: *** [build] Error 2
The command '/bin/sh -c mkdir -p /usr/src    && cd /usr/src    && git clone https://github.com/stcarrez/ada-awa.git ada-awa    && cd ada-awa    && git submodule init    && git submodule update    && ./confi
sable-shared --prefix=/usr    && make -s    && make -s install' returned a non-zero code: 2
```

It seems that the submodule ada-ado (and others) are not to the latest version.  ado-audits.ads is a relatively new file which is not in the version that is checked out (by the git submodule update command) in the ada-ado submodule.

If the intent of the Dockerfile is to build with the latest source in all submodules then a possible fix is to add --recursive --remote to the git submodule update command in Dockerfile.

That is, in Dockerfile replace
  ` && git submodule update`
with
   `&& git submodule update --recursive --remote`

If the intent of the Dockerfile is to build with the current commited submodules then a process needs to be put in place to insure that submodules are committed in the main project whenever the main project is dependent on a submodule change.

**Comment by stcarrez** [comment]
Thanks, I've integrated your suggestion. I try to keep the submodules synchronized on the main project but sometimes forget to update. I've also synchronized the main project to use latest versions of all sub-projects.
